from __future__ import annotations

from fundlab.paper.models import PaperTable, TableSpec

SCHEMA_VERSION = 1

TABLE_SPECS = (
    TableSpec(PaperTable.ACCOUNTS, ("account_id",), (("name",),)),
    TableSpec(PaperTable.CURRENT_POSITIONS, ("account_id", "ledger_version", "symbol")),
    TableSpec(PaperTable.DAILY_POSITIONS, ("account_id", "ledger_version", "trade_date", "symbol"), append_only=True),
    TableSpec(PaperTable.DECISIONS, ("decision_id",), (("account_id", "ledger_version", "decision_date"),), True),
    TableSpec(PaperTable.ORDERS, ("order_id",), append_only=True),
    TableSpec(PaperTable.FILLS, ("fill_id",), append_only=True),
    TableSpec(PaperTable.ACCOUNT_SNAPSHOTS, ("account_id", "ledger_version", "trade_date"), append_only=True),
    TableSpec(PaperTable.EVENT_LEDGER, ("event_id",), (("account_id", "ledger_version", "event_sequence"),), True),
    TableSpec(PaperTable.EXECUTION_PROFILES, ("profile_id", "version"), append_only=True),
    TableSpec(PaperTable.RISK_PROFILES, ("profile_id", "version"), append_only=True),
    TableSpec(PaperTable.DAILY_RUNS, ("account_id", "ledger_version", "trade_date"), append_only=True),
    TableSpec(PaperTable.LEDGER_VERSIONS, ("account_id", "ledger_version"), append_only=True),
    TableSpec(PaperTable.DATE_BATCHES, ("batch_id",), (("scope_key",),), immutable_when_complete=True),
)

SCHEMA_SQL = """
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS paper_execution_profiles (profile_id TEXT NOT NULL, version TEXT NOT NULL, payload_json TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(profile_id, version));
CREATE TABLE IF NOT EXISTS paper_risk_profiles (profile_id TEXT NOT NULL, version TEXT NOT NULL, payload_json TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(profile_id, version));
CREATE TABLE IF NOT EXISTS paper_accounts (account_id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, status TEXT NOT NULL CHECK(status IN ('active','paused','closed')), initial_cash REAL NOT NULL CHECK(initial_cash > 0), cash REAL NOT NULL CHECK(cash >= 0), strategy_id TEXT NOT NULL, strategy_config_version TEXT NOT NULL, universe_version TEXT NOT NULL, benchmark_symbol TEXT NOT NULL, execution_profile_id TEXT NOT NULL, execution_profile_version TEXT NOT NULL, risk_profile_id TEXT NOT NULL, risk_profile_version TEXT NOT NULL, schedule TEXT NOT NULL CHECK(schedule IN ('daily','weekly','monthly')), selected_ledger_version INTEGER NOT NULL DEFAULT 1 CHECK(selected_ledger_version > 0), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(execution_profile_id, execution_profile_version) REFERENCES paper_execution_profiles(profile_id, version), FOREIGN KEY(risk_profile_id, risk_profile_version) REFERENCES paper_risk_profiles(profile_id, version));
CREATE TABLE IF NOT EXISTS paper_ledger_versions (account_id TEXT NOT NULL, ledger_version INTEGER NOT NULL CHECK(ledger_version > 0), parent_version INTEGER, replay_reason TEXT, replay_start_date TEXT, replay_end_date TEXT, created_at TEXT NOT NULL, PRIMARY KEY(account_id, ledger_version), FOREIGN KEY(account_id) REFERENCES paper_accounts(account_id));
CREATE TABLE IF NOT EXISTS paper_date_batches (batch_id TEXT PRIMARY KEY, scope_key TEXT NOT NULL UNIQUE, trade_date TEXT NOT NULL, operation TEXT NOT NULL CHECK(operation IN ('daily','replay')), account_id TEXT, ledger_version INTEGER CHECK(ledger_version > 0), parent_ledger_version INTEGER CHECK(parent_ledger_version > 0), status TEXT NOT NULL CHECK(status IN ('running','complete','failed')), data_version TEXT NOT NULL, config_fingerprint TEXT NOT NULL, provenance_json TEXT NOT NULL, started_at TEXT NOT NULL, completed_at TEXT, error_json TEXT, CHECK((operation = 'daily' AND account_id IS NULL AND ledger_version IS NULL AND parent_ledger_version IS NULL) OR (operation = 'replay' AND account_id IS NOT NULL AND ledger_version IS NOT NULL)), FOREIGN KEY(account_id) REFERENCES paper_accounts(account_id));
CREATE TRIGGER IF NOT EXISTS paper_date_batches_completed_no_update BEFORE UPDATE ON paper_date_batches WHEN OLD.status = 'complete' BEGIN SELECT RAISE(ABORT, 'completed date batch is immutable'); END;
CREATE TRIGGER IF NOT EXISTS paper_date_batches_completed_no_delete BEFORE DELETE ON paper_date_batches WHEN OLD.status = 'complete' BEGIN SELECT RAISE(ABORT, 'completed date batch is immutable'); END;
CREATE TABLE IF NOT EXISTS paper_current_positions (account_id TEXT NOT NULL, ledger_version INTEGER NOT NULL CHECK(ledger_version > 0), symbol TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity >= 0), average_cost REAL NOT NULL CHECK(average_cost >= 0), updated_at TEXT NOT NULL, PRIMARY KEY(account_id, ledger_version, symbol), FOREIGN KEY(account_id, ledger_version) REFERENCES paper_ledger_versions(account_id, ledger_version));
CREATE TABLE IF NOT EXISTS paper_daily_positions (account_id TEXT NOT NULL, ledger_version INTEGER NOT NULL CHECK(ledger_version > 0), trade_date TEXT NOT NULL, symbol TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity >= 0), average_cost REAL NOT NULL CHECK(average_cost >= 0), close_price REAL NOT NULL CHECK(close_price >= 0), market_value REAL NOT NULL CHECK(market_value >= 0), PRIMARY KEY(account_id, ledger_version, trade_date, symbol), FOREIGN KEY(account_id, ledger_version) REFERENCES paper_ledger_versions(account_id, ledger_version));
CREATE TABLE IF NOT EXISTS paper_decisions (decision_id TEXT PRIMARY KEY, account_id TEXT NOT NULL, ledger_version INTEGER NOT NULL CHECK(ledger_version > 0), decision_date TEXT NOT NULL, source_type TEXT NOT NULL, source_id TEXT NOT NULL, config_version TEXT NOT NULL, target_weights_json TEXT NOT NULL, reason TEXT NOT NULL, data_version TEXT NOT NULL, observation_hash TEXT NOT NULL, validation_json TEXT NOT NULL, original_json TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(account_id, ledger_version, decision_date), FOREIGN KEY(account_id, ledger_version) REFERENCES paper_ledger_versions(account_id, ledger_version));
CREATE TABLE IF NOT EXISTS paper_orders (order_id TEXT PRIMARY KEY, decision_id TEXT NOT NULL, account_id TEXT NOT NULL, ledger_version INTEGER NOT NULL CHECK(ledger_version > 0), symbol TEXT NOT NULL, original_target_weight REAL NOT NULL, requested_quantity INTEGER CHECK(requested_quantity >= 0), actual_quantity INTEGER CHECK(actual_quantity >= 0), status TEXT NOT NULL CHECK(status IN ('pending','filled','partial-filled','rejected','cancelled')), outcome_reason TEXT, execution_date TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(decision_id) REFERENCES paper_decisions(decision_id), FOREIGN KEY(account_id, ledger_version) REFERENCES paper_ledger_versions(account_id, ledger_version));
CREATE TABLE IF NOT EXISTS paper_fills (fill_id TEXT PRIMARY KEY, order_id TEXT NOT NULL, account_id TEXT NOT NULL, ledger_version INTEGER NOT NULL CHECK(ledger_version > 0), fill_date TEXT NOT NULL, price REAL NOT NULL CHECK(price >= 0), quantity INTEGER NOT NULL CHECK(quantity > 0), commission REAL NOT NULL CHECK(commission >= 0), slippage REAL NOT NULL CHECK(slippage >= 0), data_version TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(order_id) REFERENCES paper_orders(order_id), FOREIGN KEY(account_id, ledger_version) REFERENCES paper_ledger_versions(account_id, ledger_version));
CREATE TABLE IF NOT EXISTS paper_account_snapshots (account_id TEXT NOT NULL, ledger_version INTEGER NOT NULL CHECK(ledger_version > 0), trade_date TEXT NOT NULL, cash REAL NOT NULL CHECK(cash >= 0), market_value REAL NOT NULL CHECK(market_value >= 0), total_asset REAL NOT NULL CHECK(total_asset >= 0), nav REAL NOT NULL CHECK(nav >= 0), benchmark_value REAL, data_version TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(account_id, ledger_version, trade_date), FOREIGN KEY(account_id, ledger_version) REFERENCES paper_ledger_versions(account_id, ledger_version));
CREATE TABLE IF NOT EXISTS paper_event_ledger (event_id TEXT PRIMARY KEY, account_id TEXT NOT NULL, ledger_version INTEGER NOT NULL CHECK(ledger_version > 0), event_sequence INTEGER NOT NULL CHECK(event_sequence > 0), trade_date TEXT NOT NULL, event_type TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, payload_json TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(account_id, ledger_version, event_sequence), FOREIGN KEY(account_id, ledger_version) REFERENCES paper_ledger_versions(account_id, ledger_version));
CREATE TABLE IF NOT EXISTS paper_daily_runs (account_id TEXT NOT NULL, ledger_version INTEGER NOT NULL CHECK(ledger_version > 0), trade_date TEXT NOT NULL, batch_id TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('running','complete','failed','skipped')), data_version TEXT NOT NULL, started_at TEXT NOT NULL, completed_at TEXT, error_json TEXT, PRIMARY KEY(account_id, ledger_version, trade_date), FOREIGN KEY(account_id, ledger_version) REFERENCES paper_ledger_versions(account_id, ledger_version), FOREIGN KEY(batch_id) REFERENCES paper_date_batches(batch_id));
"""


def initialize_schema(connection) -> None:
    connection.executescript(SCHEMA_SQL)
