core_universe:
  product_types:
    - ETF
    - MONEY_ETF
  management_types:
    - passive_index
    - smart_beta
    - passive_bond
    - passive_commodity
    - passive_money_market
    - cross_border_index
  asset_classes:
    - equity
    - bond
    - commodity
    - money_market
    - cross_border

manual_include:
  - 510300.SH
  - 510500.SH
  - 518880.SH

manual_exclude: []

